### ISSUE TITLE
how does sample_size influence the results?

### ISSUE THREAD

**Issue by bakachan19** [Docta-ai/docta#4]
Hi,

I saw there are different setups for````sample_size```` for ```hoc_cfg``` and ```detect_cfg``` in different experiments.
Some experiments use the same values: 35000 for both  for  ```hoc_cfg``` and ```detect_cfg``` in ```docta_cifar10.py``` . 
Other use different values: 15000 for  ```hoc_cfg``` and 350000  ```detect_cfg``` in ```docta_rare_pattern_cifar10.ipynb```.

I tried running ```docta_cifar10.py``` with different  ```sample_size``` values and I get different results with every different setup.

I do not quite understand how ```sample_size``` influences the results and how should I select the ```sample_size``` for a dataset.
Thank you.

**Comment by zwzhu-d** [comment]
Hi @bakachan19,

Thank you for the question. This sample size should be smaller than the number of total samples. It also should be manageable to avoid OOM. For example, given a dataset with 50k samples, 70% of the total number, i.e., 70% * 50k = 35k, would be a good choice for both performance and your CPU memory. Although the results are not completely the same by changing the sample size, the overall performance is not sensitive to the sample size. For example, the F1 score of detection should be similar for experiments with `sample_size=15000` and `sample_size=35000`. 

Please feel to let us know if you have any questions.

Best,
Zhaowei

**Comment by bakachan19** [comment]
Thank you for the answer @zwzhu-d.
