### ISSUE TITLE
对hoc, detect参数配置有疑惑

### ISSUE THREAD

**Issue by kelvennn** [Docta-ai/docta#5]
你好，感谢你的工作。我在实际使用的时候对一些代码中没有解释参数有些疑惑，比如already_2nn以及num_rounds
如果我想对40W+的43分类数据进行docta，你有建议的参数设置吗？

hoc_cfg = dict(
    max_step = 1501, 
    T0 = None, 
    p0 = None, 
    lr = 0.1, 
    num_rounds = 50, 
    sample_size = 280000,
    already_2nn = False,
    device = 'cuda'
)

detect_cfg = dict(
    num_epoch = 51,
    sample_size = 280000,
    k = 43,
    name = 'simifeat',
    method = 'rank'
)

**Comment by zwzhu-d** [comment]
Thanks for your interest in Docta. Please keep `already_2nn = False` if your input data is not presented in the following format:
```python
[
  [data_0_label_self, data_0_label_1nn, data_0_label_2nn],
  [data_1_label_self, data_1_label_1nn, data_1_label_2nn],
  ...
]
```

For hoc_cfg, `num_rounds=50` is good.
For detect_cfg, `num_epoch` can be tuned according to `sample_size`. It could be larger (e.g., 101) to fully go through all the data many times.

Please note `k` represents `k`-nn. According to my experience, `10` is a good choice for many settings. Please refer to Figure 3 of [this paper](https://proceedings.mlr.press/v162/zhu22a/zhu22a.pdf).

`sample_size` looks good.

Besides, please note the detection results may be bad when the data is long-tailed distributed.

**Comment by zwzhu-d** [comment]
> 你好，感谢你的工作。我在实际使用的时候对一些代码中没有解释参数有些疑惑，比如already_2nn以及num_rounds 如果我想对40W+的43分类数据进行docta，你有建议的参数设置吗？
> 
> hoc_cfg = dict( max_step = 1501, T0 = None, p0 = None, lr = 0.1, num_rounds = 50, sample_size = 280000, already_2nn = False, device = 'cuda' )
> 
> detect_cfg = dict( num_epoch = 51, sample_size = 280000, k = 43, name = 'simifeat', method = 'rank' )

Thanks for your interest in Docta. Please keep `already_2nn = False` if your input data is not presented in the following format:
```python
[
  [data_0_label_self, data_0_label_1nn, data_0_label_2nn],
  [data_1_label_self, data_1_label_1nn, data_1_label_2nn],
  ...
]
```

For hoc_cfg, `num_rounds=50` is good.
For detect_cfg, `num_epoch` can be tuned according to `sample_size`. It could be larger (e.g., 101) to fully go through all the data many times.

Please note `k` represents `k`-nn. According to my experience, `10` is a good choice for many settings. Please refer to Figure 3 of [this paper](https://proceedings.mlr.press/v162/zhu22a/zhu22a.pdf).

`sample_size` looks good.

Besides, please note the detection results may be bad when the data is long-tailed distributed.
